name: Release App (EXE)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write  # Necesario para crear la Release y subir archivos

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./VideoPlayerApp/VideoPlayerApp.csproj

      - name: Publish (Generate EXE)
        # Este comando crea una carpeta con todo lo necesario para que el EXE funcione
        run: |
          dotnet publish ./VideoPlayerApp/VideoPlayerApp.csproj -c Release -o ./publish --runtime win-x64 --self-contained false -p:PublishSingleFile=true -p:PublishReadyToRun=true

      - name: Zip Release
        # Comprimimos la carpeta publish para que el usuario descargue un solo archivo
        run: Compress-Archive -Path ./publish/* -DestinationPath ./DJ_Isla_Player_Windows.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./DJ_Isla_Player_Windows.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
